name: Dep Checker

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *' # Every day at 00:00

jobs:
  Dep-Checker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout dep-checker
      uses: online-applications/dep-checker@v1
      with:
        jira_host: your-domain.atlassian.net
        jira_user: example@your-domain.com
        jira_token: ${{ secrets.jira_token }}
        jira_project: PRJ
        jira_issue_type: Story
        jira_epic_id: EPC-123
        level: major
        npmrc: |
          //npm.pkg.github.com/:_authToken=${{ secrets.access_token_github }}
          @private-scope:registry=https://private.registry.com/
        netrc: |
          machine github.com
          login ${{ secrets.access_token_github }}
          password x-oauth-basic
        ignore: |
          public/**
