name: Dep Checker

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *' # Every day at 00:00

jobs:
  Dep-Checker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout dep-checker
      uses: online-applications/dep-checker@v1.0.5
      with:
        jira_host: risecodes.atlassian.net
        jira_user: search-service-user@risecodes.com
        jira_token: ${{ secrets.jira_service_user_token }}
        jira_project: RIS
        jira_issue_type: Story
        jira_epic_id: DGDT-1232
        ignore: |
          public/**