name: Dep Checker

on:
  schedule:
  - cron: '0 0 * * 0' # Every Sunday at 00:00

env:
  JIRA_TOKEN: ${{ secrets.jira_service_user_token }}
  DEP_CHECKER_VERSION: v1.0.0
  # Uncomment to change default values
  # JIRA_USER: search-service-user@risecodes.com
  # JIRA_PROJECT: RIS
  # JIRA_ISSUE_TYPE: Story
  # DEP_CHECKER_LEVEL: major
  # DEP_CHECKER_IGNORE:

# Inspired by
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-an-action-inside-a-different-private-repository-than-the-workflow
jobs:
  Deps-Checker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout dep-checker
      uses: actions/checkout@v3
      with:
        repository: online-applications/dep-checker
        ref: ${{ env.DEP_CHECKER_VERSION }}
        token: ${{ secrets.access_token_github }}
        path: ./.github/actions/dep-checker
    - name: Check updates
      uses: ./.github/actions/dep-checker
      # with:
      #   level: major
