name: Dependencies Checker

on:
  schedule:
  - cron: '0 0 * * 0' # Every Sunday at 00:00

env:
  JIRA_TOKEN: ${{ secrets.jira_service_user_token }}

# Inspired by
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-an-action-inside-a-different-private-repository-than-the-workflow
jobs:
  Deps-Checker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout dep-checker
      uses: actions/checkout@v3
      with:
        repository: online-applications/dep-checker
        token: ${{ secrets.access_token_github }}
        path: ./.github/actions/dep-checker
    - name: Check updates
      uses: ./.github/actions/dep-checker
