name: Build

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Calculate version
      id: version
      uses: online-applications/version-action@v2.1.0
      env:
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        ENVIRONMENT: ${{ github.ref_name != 'main' && 'staging' || 'production' }}
    - name: Build
      run: npm i && npm run build
    - name: Push Tag
      run: |
        VERSION=v1.0.3-rc
        echo "Version: $VERSION"
        if [[ $(git status --porcelain) ]]; then
          git add .
          git config user.name "GitHub Actions"
          git config user.email github-actions@github.com
          git commit -am "Bumping $VERSION"
          echo Added commit: '"'Bumping $VERSION'"'
        fi
        set -x
        git tag $VERSION
        git push -f origin $GITHUB_REF_NAME $VERSION
