name: Deploy

on: workflow_dispatch

jobs:
  Version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      repo_version_env: ${{ steps.version.outputs.repo_tag }}
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Calculate version
      id: version
      uses: online-applications/version-action@v2.0.0
  Lint:
    name: Lint code
    runs-on: ubuntu-latest
    needs: Version
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Authenticate with private NPM package
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
    - name: Lint code
      run: |
        echo "npm ci"
        npm ci
        echo "run lint"
        npm run lint
  Push-Tag:
    name: Push New Tag
    runs-on: ubuntu-latest
    needs: [Version, Lint]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Push version
      run: |
        git tag ${{ needs.Version.outputs.repo_version_env }}
        git push --tags
